# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('H', 'high'), ('N', 'normal'), ('L', 'low')], default='normal', max_length=100)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
